# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-14 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 14, 21, 55, 2, 570327, tzinfo=utc), null=True),
        ),
    ]
