# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-14 23:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200114_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 14, 23, 32, 18, 117538, tzinfo=utc), null=True),
        ),
    ]
